service: tg-language-bot

# throw error before trying to deploy if something is wrong in config
configValidationMode: error

# create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  region: eu-central-1
  environment:
    TELEGRAM_TOKEN: ${ssm:/tg-language-bot-token}

functions:
  bot:
    handler: src/lambda/bot.handler
    events:
      - http:
          method: post
          path: bot
          cors: true

  setCommands:
    handler: src/lambda/setCommands.handler
    events:
      - http:
          method: post
          path: setCommands
          cors: true